/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clock;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Lenovo
 */
public class clock extends javax.swing.JFrame {

    /**
     * Creates new form clock
     */
    public clock() {
        initComponents();
        
        Thread t1 = new Thread(){
          public void run(){
              while(true){
                  DateFormat date = new SimpleDateFormat("hh : mm : ss aa");
                  
                  String datestring = date.format(new Date()).toString();
                  
                  clockname.setText(datestring);
                  
                  
                  try{
                      Thread.sleep(1);
                  }catch(Exception e){
                  }
              }
          }  
        };
       
        Thread t2 = new Thread(){
          public void run(){
              while(true){
                  DateFormat date1 = new SimpleDateFormat("dd - MM - yyyy");
                  
                  String datestring1 = date1.format(new Date()).toString();
                  
                  clockname3.setText(datestring1);
                  
                  
                  try{
                      Thread.sleep(1);
                  }catch(Exception e){
                  }
              }
          }  
        };
        t1.start();
        t2.start();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockname = new javax.swing.JLabel();
        clockname3 = new javax.swing.JLabel();
        imglabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital___Clock");
        setPreferredSize(new java.awt.Dimension(510, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clockname.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        clockname.setForeground(new java.awt.Color(255, 153, 0));
        clockname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(clockname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 490, 130));

        clockname3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        clockname3.setForeground(new java.awt.Color(255, 153, 0));
        clockname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(clockname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 490, 130));

        imglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock/55220_original_2560x1600.jpg"))); // NOI18N
        imglabel.setMaximumSize(new java.awt.Dimension(2560, 1600));
        imglabel.setMinimumSize(new java.awt.Dimension(2560, 1600));
        getContentPane().add(imglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 450));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 253, 340, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockname;
    private javax.swing.JLabel clockname3;
    private javax.swing.JLabel imglabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
